### ISSUE TITLE
FEATURE_REQUEST add support for animated webp

### ISSUE THREAD

**Issue by beh-10257** [Horus645/swww#111]
since webp format accepts animation why not use it + the file size is considerably smaller

**Comment by Horus645** [comment]
This would need to be supported by the `image` crate for us to use it, but it should be fairly easy.

**Comment by beh-10257** [comment]
@Horus645 there are a lot of talk about the animated webp in the image crate is it already supported
exemple of issues
https://github.com/image-rs/image/issues/1893
+
there is this pull request I guess it's already supported

**Comment by AdsonCicilioti** [comment]
And WebP static? Looks a good start.

**Comment by Horus645** [comment]
@AdsonCicilioti it seems the image crate has gained support for WebP static, so it should on next release when I bump our dependencies.
