### ISSUE TITLE
Crash in Hyprland

### ISSUE THREAD

**Issue by YinAqu** [Horus645/swww#115]
swww works well in sway on my laptop, but I switch to Hyprland recently. is there any log for swww that i can check?
```
os: archlinux 
swww: 0.7.2
hyprland: 0.24.1
```

**Comment by flick0** [comment]
how are u starting swww on hyprland

**Comment by YinAqu** [comment]
@flick0 just now i reinstalled hyprland to updated it to the `git master` version, and everything seems ok, should be a bug of version `0.24.1`. thx for your gorgeous work, the smooth transition effect is so good!!
