### ISSUE TITLE
Error when setting large wallpapers

### ISSUE THREAD

**Issue by Aiz0** [Horus645/swww#12]
When setting image with a big disk size such as 4K wallpapers.
I used this one: https://www.pexels.com/photo/bird-s-eye-view-of-city-2246476/

I get this error before the wallpaper gets set:
`Error: "Failed to receive answer: io error: Resource temporarily unavailable (os error 11)"`

The wallpaper still gets displayed correctly.

**Comment by Horus645** [comment]
I cannot reproduce this.

Since the wallpaper gets displayed correctly, I believe it is a simple problem of the timeout being too low.

**Comment by Horus645** [comment]
@Aiz0 can you please check if the problem remains in [PR 14](https://github.com/Horus645/swww/pull/14)? Since I can't seem to be able to reproduce the error anyway...

**Comment by Aiz0** [comment]
It seems I was using version `0.2.0` despite AUR package being `0.3.0`.
Might be an issue with the provided `tar.gz` but idk.

on version `0.3.0` I can only reproduce it with large lossless WebP images.
Those are rendered weird anyways.

**Comment by Aiz0** [comment]
I do not get the error even on those large lossless WebP images after building #14
