### ISSUE TITLE
Can't control swww using cron

### ISSUE THREAD

**Issue by SDD701** [Horus645/swww#122]
Hello I want to switch my wallpapers for example every hour using cron, but it seems I can't control swww using it.

What I do:
``exec=swww init`` in my wayland compositor's config

And the script that I launch in crontab:
```
/home/SDD/.local/bin/wal -i /home/SDD/Wallpapers/
swww img "$(< "/home/SDD/.cache/wal/wal")"
```

Logs of the script execution:
```
Error: "Socket file not found. Are you sure swww-daemon is running?"
```

If I kill/init swww in the script I get the same error, but when I launch it from terminal all works fine. Am I missing something or this is a bug? Thank you in advance.

**Comment by Horus645** [comment]
If the script is telling you the daemon isn't running, then the problem is that `exec=swww init` isn't working. This can sometimes happen if the compositor runs these commands before the whole compositor state is set up (so `swww` can't listen in to output yet, for example). I think someone else had a similar problem before, I'll see if I can find it.

**Comment by uncomfyhalomacro** [comment]
The only way to do that is to check if `WAYLAND_DISPLAY` is set before running `swww`

**Comment by SDD701** [comment]
> If the script is telling you the daemon isn't running, then the problem is that `exec=swww init` isn't working. This can sometimes happen if the compositor runs these commands before the whole compositor state is set up (so `swww` can't listen in to output yet, for example). I think someone else had a similar problem before, I'll see if I can find it.

I've forgotten to mention, swww img is working with this exec, I can use swww img interactively.  Also if I try to not init it in exec, but in the cron script, even for the first time the log outputs:

```
Error: "Failed to connect to socket: Connection refused (os error 111)"
Error: "Failed to connect to socket: Connection refused (os error 111)"
```

**Comment by SDD701** [comment]
> The only way to do that is to check if `WAYLAND_DISPLAY` is set before running `swww`

My WAYLAND_DISPLAY is "wayland-1". I've added in the compositor's config before swww init: 
```
exec=export WAYLAND_DISPLAY="wayland-1"
```
and in the script that cron is launching:
```
export WAYLAND_DISPLAY="wayland-1"
```
but it seems still not working. Am I doing it wrong?

**Comment by SDD701** [comment]
After executing this in the script:
```
rm -vrf /tmp/swww && export XDG_RUNTIME_DIR="/run/user/1000" && swww init --no-daemon
```

I see this output in the logs, despite I've completely removed any inits from compositor's config
```
removed '/tmp/swww/swww.socket'
removed directory '/tmp/swww'
thread 'main' panicked at 'Failed to connect to wayland environment: NoCompositorListening', daemon/src/wayland.rs:51:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Maybe it could help

**Comment by uncomfyhalomacro** [comment]
> > The only way to do that is to check if `WAYLAND_DISPLAY` is set before running `swww`
> 
> My WAYLAND_DISPLAY is "wayland-1". I've added this in the compositor's config before swww init:
> 
> ```
> exec=export WAYLAND_DISPLAY="wayland-1"
> ```
> 
> and in the script that cron is launching:
> 
> ```
> export WAYLAND_DISPLAY="wayland-1"
> ```
> 
> but it seems still not working. Am I doing it wrong?

you're doing it wrong. What i meant was if `WAYLAND_DISPLAY` is *set by a compositor*, run `swww`

**Comment by uncomfyhalomacro** [comment]
You shouldn't set the `WAYLAND_DISPLAY` yourself as that is set by the Wayland compositor you are using. Unless you are spawning stuff from a running Wayland compositor while you are in a different tty session assuming you know what value their `WAYLAND_DISPLAY` is. You can also use a systemd.timer as well and make it run only if `WAYLAND_DISPLAY` is available.

**Comment by SDD701** [comment]
So, I've done some researches. The problem was the limited environment that crontab runs on. so cycle sleep until `WAYLAND_DISPLAY` is set is pointless, because cron job wouldn't see it anyway (despite whoami returns my login when running a cron script). Possible workaround is to use `at` command to set up a schedule  in the script and then run it when the compositor is starting up. 

If this would work, I'll paste here my files, so anyone for the same problem could use it, If it would have the same problems, then I guess swww is not designed for that kind of automatization and I need to PR/fork some fixes to locate existing daemon and control it in any environment

**Comment by uncomfyhalomacro** [comment]
yes crontab doesnt support it. u can only run it based on time. what u can do is use systemd timers. i havent explored it yet

**Comment by SDD701** [comment]
Also a good idea might be to use pywal as a cron job and for swww use [inotify-tools](https://github.com/inotify-tools/inotify-tools) in a constantly running background script, that is initialized at the compositor startup, to listen if `~/.cache/wal/wal` is changed and if it has been changed, swww img to the path located there.
