### ISSUE TITLE
error when trying to add daemon

### ISSUE THREAD

**Issue by GearToward** [Horus645/swww#124]
I keep getting this when trying to activate daemon
using Fedora 38
Error: "error spawning swww-daemon: No such file or directory (os error 2)"

**Comment by Horus645** [comment]
Are you running `swww init`? In that case, make sure the `swww-daemon` binary is in your `$PATH`.

**Comment by GearToward** [comment]
I found my solution but forgot to close the issue and I had to add it to my shel/path
