### ISSUE TITLE
"--transition-type grow --transition-pos" not working correctly

### ISSUE THREAD

**Issue by helixoid** [Horus645/swww#127]
OS: Arch Linux
WM: Hyprland 0.26.0
swww 0.7.3

**_swww img <path/to/image> --transition-type grow --transition-pos "$(hyprctl cursorpos)" --transition-fps 60 --transition-duration 3_**

This should in theory follow the mouse cursor and start it's animation from there but it is inverted in y-axis.
For eg: If my cursor position is in upper half of monitor the swww wallpaper changing animations starts from just opposite side i.e. lower half of monitor but x-axis is same.

I have watched videos of rices with Hyprland before but swww was working as expected but when I am using it, it's not working the same way.

Here is the script that I run with a keybinding to change the wallpaper at will:-

#!/bin/bash

DIR=$HOME/Pictures/Walls/
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

swww init
swww img ${DIR}/${RANDOMPICS} --transition-type grow --transition-pos "$(hyprctl cursorpos)" --transition-fps 60 --transition-duration 3

**Comment by Horus645** [comment]
Wait, people are making videos with `swww`? Damn...

In any case, are you sure no transformation is being applied to your monitor? Can you paste the output of `wlr-randr`?

**Comment by helixoid** [comment]
> Wait, people are making videos with `swww`? Damn...
> 
> In any case, are you sure no transformation is being applied to your monitor? Can you paste the output of `wlr-randr`?

❯ wlr-randr
eDP-1 "BOE 0x0674 (eDP-1)"
  Make: BOE
  Model: 0x0674
  Serial: (null)
  Physical size: 340x190 mm
  Enabled: yes
  Modes:
    1366x768 px, 59.999001 Hz (preferred, current)
    1366x768 px, 47.979000 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled

**Comment by helixoid** [comment]
> Wait, people are making videos with `swww`? Damn...
> 
> In any case, are you sure no transformation is being applied to your monitor? Can you paste the output of `wlr-randr`?

I not that technical but I want to say that wallpaper changing animations are working but --transition-pos "$(hyprctl cursorpos)" should follow the cursor around and grow animation style's origin point should be the output os hyprctl cursorpos, but that's not happening.

It is only follwing the cursor in x-coordinate and is inverted in y-coordinate.

Really sorry if you are unable to understand me, as I am not a native eng speaker.
But if you want I can also make a video and post it here.

**Comment by flick0** [comment]
ah that might be on me, I remember inverting the y axis based on how hyprland used to do it but I think its been updated and it isnt the same anymore, it should be a simple fix but the decision is gonna depend on @Horus645 since inverting y axis again might break other scripts(that dont use hyprctl)

**Comment by helixoid** [comment]
Here is a video example of how it is working currently:-

[Imgur](https://imgur.com/SoEf6VS)

**Comment by Horus645** [comment]
> Really sorry if you are unable to understand me, as I am not a native eng speaker.

No no, don't worry about that, you've been perfectly clear and I understand the problem :).

@flick0, I think we can just add a `invert-y-axis` flag. So people can just use that when calling `swww img`. This should also solve all future problems that might arise from this.
