### ISSUE TITLE
`swww-daemon` exits when running `swww clear`

### ISSUE THREAD

**Issue by HakierGrzonzo** [Horus645/swww#131]
Hello, while packaging the new version of `swww` I run into some issues.

# Environment:

```
~ $ swww query
DP-2: 2560x1440, scale: 2, currently displaying: color: 000000
HDMI-A-1: 2560x1080, scale: 1, currently displaying: color: 000000
```

```
~ $ swww --version
swww 0.8.0
```

# How to reproduce:

1. Start `swww-daemon`
2. Run `swww clear`

swww should exit with a message like this:

```
fish: Job 1, 'swww-daemon' terminated by signal SIGUSR1 (User defined signal 1)
```

**Comment by Horus645** [comment]
wtf. Wait a minute, this is probably something incredibly stupid
