### ISSUE TITLE
swww init can't restore previous selected wallpaper upon reboot or logout & log back in.

### ISSUE THREAD

**Issue by helixoid** [Horus645/swww#133]
OS: Arch Linux
Version: 0.8.0

On the previous version when I ran swww init then it restored the wallpaper set on previous session.
But now, when I open Hyprland then it doesn't (swww init is set to execute on Hyprland startup).
And also, there's a black strip on the top portion of monitor where wallpaper is not drawn.

![2023-07-12-11:08:21](https://github.com/Horus645/swww/assets/110732140/ab75a793-6a08-41a7-a7ce-252e7331a42d)

![2023-07-12-11:08:12](https://github.com/Horus645/swww/assets/110732140/14c8b29d-5554-4646-858a-f187ef32fee1)

Here is the srcipt that I run:

```
#!/bin/sh

DIR="$HOME/Pictures/Walls/"

BG="$(find "$DIR" -name '*.jpg' -o -name '*.png' -name '*.webp' | shuf -n 1)"

PROGRAM="swww-daemon"

if pgrep "$PROGRAM" >/dev/null; then
	swww img "$BG" --resize fit --transition-fps 60 --transition-type grow --transition-pos "$(hyprctl cursorpos)" --invert-y --transition-duration 2
else
	swww init && swww img "$BG" --resize fit --transition-fps 60 --transition-type grow --transition-pos "$(hyprctl cursorpos)" --invert-y --transition-duration 2
fi
```

**Comment by Horus645** [comment]
The black strip is #132.

As for the wallpaper not being set on init, this is actually intentional. I was having annoying problems with it.

I've just thought of a new way of trying to implement it though. I will give it a go.
