### ISSUE TITLE
Laggy animated wallpapers and leaving artifacts 

### ISSUE THREAD

**Issue by krypciak** [Horus645/swww#135]
After updating to the latest version: `swww 0.8.0-master`, my .gif has been laggy and glitchy.
Here's the command I use:
```bash
swww img --filter Nearest MemoryOfaDistantPlace.gif
```
I attached the gif below
![MemoryOfaDistantPlace](https://github.com/Horus645/swww/assets/115574014/a19b97af-a583-421e-962a-e0fb404dfc81)
![image](https://github.com/Horus645/swww/assets/115574014/89faabbe-f749-417a-bc26-8e072cee2e22)

**Comment by Horus645** [comment]
Might be related to #132.

Good news is, this one I actually managed to reproduce:

![image](https://github.com/Horus645/swww/assets/73939669/becad198-c2c5-4e3b-8fb6-8287e1602a44)
 
 (it looks kind of interesting, in a way. Hahahahaha)
