### ISSUE TITLE
Wallpaper leaving empty space behind bars

### ISSUE THREAD

**Issue by 1Arsna1** [Horus645/swww#138]
On EWW and Waybar no matter which layer they are set too (overlay,top,bottom,bg,fg).
The wallpaper does not fill the entire screen it leaves an empty space directly below the bar which size depends on the bar size.
Reinstalling, restarting and fiddeling with the config of the bars and reinstalling swww did not help, using the new flags did not help and after going back to 0.7.3 it worked again like it used to be

**Comment by Horus645** [comment]
Sounds like a variation of #132. I also can't reproduce this.

> an empty space directly below the bar which size depends on the bar size

This is interesting, new information. I suggest you have a look at #132 to see if the issue is the same and we can continue troubleshooting there.

**Comment by lokesh-krishna** [comment]
![image](https://github.com/Horus645/swww/assets/20235646/8a30d24e-f890-490a-86d6-7941fc295a03)

Bar associated dark space here as well. What additional info can I provide?

**Comment by Horus645** [comment]
This is almost certainly fixed alongside #132 with the newest commit. I have one last thing to fix and I will release a minor version.
