### ISSUE TITLE
error[E0658]: use of unstable library feature 'once_cell'

### ISSUE THREAD

**Issue by erlonbie** [Horus645/swww#145]
Hi, I tried to upgrade from 0.7.3-0 to 0.8.1-0 and got the error on the title.

![image](https://github.com/Horus645/swww/assets/50176483/465e6632-b545-4a60-981d-8ca29466e9cf)

**Comment by Horus645** [comment]
Update your rust toolchain to the latest version. OnceCell was stabilized in rust 1.70.0.

**Comment by erlonbie** [comment]
Thank you! I'll close this.
