### ISSUE TITLE
Use swww as systemd service

### ISSUE THREAD

**Issue by OopsYao** [Horus645/swww#149]
I used `swww --no-daemon` as a systemd service, which stops working after v0.8.0/0.8.1, because, as @Horus645 pointed out in https://github.com/Horus645/swww/issues/144#issuecomment-1638335866,

> the daemon is no longer responsible for loading the cache during initialization.

And I came to realize that the "right" way to use `swww init` as a service is the *oneshot* service with `RemainAfterExit` option, which works well at v0.8.1 and no black screen appears as in #144. I'd like to share it here if anyone is interested.

```
[Unit]
Description=A Solution to your Wayland Wallpaper Woes
# The target may not be what you need, change it accordingly
PartOf=wayland-session.target
After=wayland-session.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/swww init
# Choose a random wallpaper if you want
#ExecStartPost=/path/to/your/random_wallpaper_script

[Install]
WantedBy=wayland-session.target
```
And here is an example of `random_wallpaper_script`
```bash
#!/usr/bin/env bash

swww img "$(ls /path/to/your/wallpapers/*.{png,jpg,gif} | shuf -n 1)"
```

**Comment by Aiz0** [comment]
Would using `Type=forking` be applicable here?
```
[Service]
Type=forking
ExecStart=swww init
ExecStop=swww kill
```

**Comment by OopsYao** [comment]
Yes, that works, and I even think it is more appropriate and natural, at least in terms of semantics.
