### ISSUE TITLE
Source of wallpapers used in README.md?

### ISSUE THREAD

**Issue by ncfavier** [Horus645/swww#151]
Please add links to the sources of the wallpapers used in the README in the acknowledgements section. (I'm looking for the "gradient" one in particular but it's nice to give credit anyway)

**Comment by Cephian** [comment]
Just because I recognized it myself, the pixel art one is from the artist Waneella and a lossless GIF version is available on her Patreon page

**Comment by flick0** [comment]
The gradient one is from this nice wallpaper pack at https://www.behance.net/gallery/86128681/Free-Unicorn-Vector-Gradients

**Comment by Horus645** [comment]
@flick0, do you have a source for the other wallpaper you used in the README? Besides the gradient one?

**Comment by Horus645** [comment]
Updated the README.
