### ISSUE TITLE
Version 0.4.0 streches the wallpaper

### ISSUE THREAD

**Issue by HakierGrzonzo** [Horus645/swww#16]
Hi! Thanks for working on this fun little program!

I have found a bug/regression between versions 0.3.0 and 0.4.0.

# Issue

There is an undocumented change when scaling the wallpaper image. In `0.3.0` swww used to `fill` the wallpaper, now it `strech`es the image.

## On version `0.4.0` and `master`

**When** The requested wallpaper image has a different aspect ratio then the target output.
**Then** The displayed image is _stretched_.

## On version `0.3.0`

**When** The requested wallpaper image has a different aspect ratio then the target output.
**Then** The displayed image is _zoomed in_.

Can we return the old behavior or turn it into an option?

# Environment:
```
$ swww query
DP-2 = 2560x1440, currently displaying: image: "wallpaper.bmp"
HDMI-A-1 = 2560x1080, currently displaying: image: "wallpaper.bmp"
```
- Window manager - `sway`
- `DP-2` is a 16:9 4k screen with `1.5` scaling, `HDMI-A-1` is a 21:9 ultrawide.
- `wallapaper.bmp` is a 1080p 16:9 image.

**Comment by Horus645** [comment]
This is an unfortunate consequence of using the `fast-image-resize` crate to resize the image, as opposed to the `image` crate solutions. I might be able to reproduce the old behavior by doing the zoom sort of manually.

You are right in that I should have documented this. That was my bad.

**Comment by Horus645** [comment]
UPDATE: I was being a dumb dumb. `fast-image-resize` literally has an example of resizing while cropping the image in the front page of its documentation.

PR coming soon.
