### ISSUE TITLE
Background goes black when I unplug external monitor

### ISSUE THREAD

**Issue by bluthej** [Horus645/swww#170]
## Problem

Whenever I unplug an external monitor (plugged in via hdmi) the background goes black.

## Additional info

When I look at the running processes, swww-daemon seems to be killed whenever I unplug an external monitor, which I assume is the root of the problem. If I run `swww init` the wallpaper comes back until I plug and unplug an external monitor again.

I'm not sure where to look for log files and whatnot for swww so I don't have a lot more info, but I'm happy to provide whatever I can if given appropriate instructions.

## Setup

Running hyprland on Arch. 

I don't have anything fancy regarding monitors in my hyprland setup so I assume this is an issue with swww but I might be wrong.

**Comment by tincaMatei** [comment]
Just about to write the same issue. I ran into the same problem:

After running:

> swww init --no-daemon

and then disconnecting one of the monitors from my laptop, I get the following output:

```
23:10:09 [INFO] (main) Initialization succeeded! Starting main loop...
Protocol error 0 on object wl_display@1: invalid object 11
thread 'main' panicked at daemon/src/main.rs:110:31:
failed to read the event queue: Protocol(ProtocolError { code: 0, object_id: 1, object_interface: "wl_display", message: "invalid object 11" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
23:10:25 [INFO] (main) Removed socket at "/run/user/1000/swww.socket"
```

Also running Hyprland on Arch.

**Comment by Nick1296** [comment]
Same behavior on NixOS 23.11

**Comment by bluthej** [comment]
I am not experiencing this issue anymore, but there hasn't been any change to swww in a bit so I don't think this was related to swww.

@tincaMatei and @Nick1296 are you still having this problem? If not I will close the issue.

**Comment by tincaMatei** [comment]
Actually me neither, I don't know what caused the problem.

**Comment by Nick1296** [comment]
Just tested, now everything seems to be fine on my end
