### ISSUE TITLE
`--transition-duration` to control transition duration

### ISSUE THREAD

**Issue by WhyNotHugo** [Horus645/swww#30]
### Description

Currently the speed of the transition must be configured via `--transition-step` and `--transition-speed`. Tweaking these values require some pretty delicate understanding of the how transitions are implemented, keeping in mind screen resolution, and possibly some basic math.

I believe the current approach is designed this way since it directly exposes the internals of  the transitions implementations.

### Possible improvement

I'd like to propose merging these into a `--transition-duration` flag, which merely takes an integer with the transition duration in milliseconds. This is something a lot "friendlier" and handles just one value that's very simple to understand.

The correct values for `transition-speed` and `transition-step` can be calculated based on `--transition-duration` and `--transition-fps`.

**Comment by Horus645** [comment]
Hm. I like the overall idea. I will think about it some more. I worry a bit about the user asking for impossible things. Like `--transition-fps 60 --transition-duration 1000000`. I am pretty sure no transition at 60fps would *ever* take 1000 seconds to complete (that's 16 minutes!). Right now something like this is impossible, since the highest possible values for the options we expose is `255`. But, if we would allow for a `duration` flag in miliseconds we would have to allow for larger values.

**Comment by Horus645** [comment]
As an update, @flick0 had a PR some time ago that added a `transition-speed` option. Combining that with our other options we might be able to do something about this. They actually ended up closing the PR, but I liked the idea so even if they don't reopen it, I will probably do it myself.

**Comment by flick0** [comment]
> As an update, @flick0 had a PR some time ago that added a `transition-speed` option. Combining that with our other options we might be able to do something about this. They actually ended up closing the PR, but I liked the idea so even if they don't reopen it, I will probably do it myself.

i had closed that pr cuz i thought bezier curves wud replace `--transition-speed`, i can try adding --transition-duration too in the bezier pr im wrking on

**Comment by Horus645** [comment]
No no, this is something for later. First we need to solve the bezier curves thingy, later we can try our hands at this.

**Comment by flick0** [comment]
> No no, this is something for later. First we need to solve the bezier curves thingy, later we can try our hands at this.

i added `--transition-duration` to [this](https://github.com/Horus645/swww/pull/50) pr, it kind of naturally came with the beziers with not alot of extra work
