### ISSUE TITLE
Choose display method for images smaller than your display size

### ISSUE THREAD

**Issue by a-priestley** [Horus645/swww#37]
I've noticed that if you display an image that has a lower resolution than your native display res, swww defaults to stretching the image to fill the display. Is it feasible to implement the option to centralize the image instead, filling the border with a color of your choice?

**Comment by Horus645** [comment]
Hi!
This seems to be in a weird limbo between being not too complicated for me to say 'no' outright, but not too simple that I can just do it really quickly. One of the problems would be the speed of doing these operations. I don't know if the image crate has something to help do this...

In any case, I can certainly give it a go, though it will take a while (I want to solve #26, and that one is looking to be really annoying + I've been full of work lately).

**Comment by a-priestley** [comment]
I didn't noticed this until I hooked up a second monitor, but the `--no-resize` option seems to cause image distortion if different output sizes are used. On a 1440p display, the 1080p image will be resized correctly, but the image will be warped on a second, 1080p display.
