### ISSUE TITLE
Span image over all monitors.

### ISSUE THREAD

**Issue by FF-AntiK** [Horus645/swww#39]
Would it be possible to allow an image to be spanned over multiple monitors?
I could try to implement this myself. I would just need a hint, where in the code the image is drawn on a specific output.
I gues I would just need to split the image data into `n` chunks and then send them to the appropriate outputs.

**Comment by Horus645** [comment]
I think this would actually be pretty difficult with the way we organized the code. Let me think about it a little.

**Comment by FF-AntiK** [comment]
For now I just split the image manually and then send the chunks to the appropriate monitor with `swww`, which works good enough.
The only thing I might have to consider with this approach is, that the animation isn't synced on both monitors. Do you think it would be possible to allow sending both images to their corresponding outputs in one command, to make sure the animation starts at the same time on both outputs?

**Comment by FF-AntiK** [comment]
Any news on this? I'm very happy with my solution so far. But syncing the frame numbers on both monitors would still be very nice. Sometimes they are out of sync because they wont start exactly the same time.

**Comment by Horus645** [comment]
Syncing is precisely the problem. I am actually surprised it works sometimes at all! I am thinking of adding an option `--span-all`, or something like that, that will allow you to send one image meant to spawn across all monitors. Then we can synchronize everything only in this specific case.

I am thinking of adding barriers for the animation threads in this case, but I still need to flesh out all the details . There's also some other things that I will probably get to first, such as #42 and #37 (since they are simpler), and reviewing PR 44 (since it might change some stuff inside animation).

Unfortunately, I will remain very busy at least until early December, so I've been working slowly on everything, and I think this particular request will still take while :(

**Comment by FF-AntiK** [comment]
No problem! I'm happy you consider this at all ;-)
For now I'll use this little startup script:
```sh
#!/bin/sh
if [ -z "$1" ]
then
	IMG=$(ls -d ~/Pictures/wallpapers/* | shuf -n 1)
else
	IMG=$(realpath "$1")
fi

WIDTH=$(identify -format '%[fx:w/2]' "$IMG"'[0]')
HEIGHT=$(identify -format '%[fx:h]' "$IMG"'[0]')

convert "$IMG" -coalesce -repage 0x0 -crop "$WIDTH"x"$HEIGHT"+0+0 +repage /tmp/left.gif
convert "$IMG" -coalesce -repage 0x0 -crop "$WIDTH"x"$HEIGHT"+"$WIDTH"+0 +repage /tmp/right.gif

swww init
swww img -f Nearest -o DP-3 /tmp/left.gif
swww img -f Nearest -o HDMI-A-1 /tmp/right.gif
```

As I said, sometimes it's out of sync, but then I run the script again until both GIFs seem synced. At least they don't drift away from each other as far as I can tell ;-)

**Comment by Horus645** [comment]
Hey @FF-AntiK, just as an update, since #57 greatly simplifies the daemon's code, just syncing the updates should actually become relatively simple. 

Splitting the image ourselves however, will still take a little longer.

It took a while, but we are getting there!

**Comment by FF-AntiK** [comment]
Thank you very much for working on this!

I think while syncing the gif frame numbers on multiple displays is a good idea, the image splitting should be up to the user and must not be implemented in `swww`.

The image splitting can become a bit complicated when the user has monitors with different screen sizes and/or aspect ratios. Also there are plenty of different positioning schemes I could think of...

**Comment by AdsonCicilioti** [comment]
I stumbled upon the lack of this functionality and when searching I found this issue.

 It's a shame we don't see this functionality yet.  I'll have to make do with the trick of splitting the image.

 Unfortunately, currently, we still don't have any tool for Wayland WM/composers that does this, so I'm glad that `swww` is already on the way to having it.
