### ISSUE TITLE
[Appreciation] WOW

### ISSUE THREAD

**Issue by uncomfyhalomacro** [Horus645/swww#41]
Hello. Greetings. I have fun using your wallpaper daemon. I can't believe after it caches a 315MB high-quality gif file, it hovers around 15% cpu usage (Yes I know I can use a smaller one like your demo gif so it hovers around 2-8% but still **wow**). I have submitted this to the openSUSE X11:Wayland repository to share your tool. 

Again. Thanks for creating this wonderful tool! :partying_face:

**Comment by KyleUltimate** [comment]
hmm ,for "issues" like this, I wonder should we enable the Discussion tab?

**Comment by Horus645** [comment]
Awww, thank you so much, @uncomfyhalomacro! It's good to know all that time I put into trying to make it efficient has paid off! 

---
> hmm, for "issues" like this, I wonder should we enable the Discussion tab?

I think we are fine for now. I'll enable it if we start getting a lot of attention and it gets in the way of the "real" issues. I'd rather keep things simple for the time being.
