### ISSUE TITLE
How to make UHD image fit to screen

### ISSUE THREAD

**Issue by dedguy21** [Horus645/swww#67]
I have some larger U/HD images that exceed the screen real estate when using this tool. 

What commands are available to make it only fit to screen (usually called stretch or fit)

**Comment by Horus645** [comment]
`swww` will do that automatically. It will resize and crop the image accordingly. If you want fine-grained control, then you should do it with a proper image editing tool.

**Comment by Horus645** [comment]
There hasn't been any update to this in over a month. Since it appears this arose from a misunderstanding of what `swww` does, I will be closing it.
