### ISSUE TITLE
Crashes with FFMPEG gifs

### ISSUE THREAD

**Issue by Froloket64** [Horus645/swww#68]
Hey, I recently decided to make my own wallpaper gif with `ffmpeg`, but whenever I run `swww init` and `swww img path/to/the/gif` it displays the first frame with the fading in animation and drops to default Sway background (I use Sway). 

The [gif](https://imgur.com/a/r87O9EU).

I used this command to get the gif _(However, I used other commands to get the `input.gif`)_:
``` sh
ffmpeg -i input.gif -filter_complex "fps=30,scale=1920:1080,split[a][b]; [a]palettegen=stats_mode=full [palette]; [b][palette]paletteuse=dither=sierra2_4a" output.gif
```

``` sh
$ swww --version
swww 0.6.0
```

**Comment by Horus645** [comment]
The problem seems to be that your command is generating some frames that are identical between themselves. This is rather wasteful, since the `gif` format allows you to specify the duration for every frame individually (so, instead of repeating the frames, you could just say that it lasts longer). Nevertheless, the daemon still shouldn't panic in this case.

**Comment by Froloket64** [comment]
Thanks for a quick reply and a fix! I get the issue, but that would be amazing if you could suggest a solution to the gif encoding problem with my `ffmpeg` usage, that's my second day using it. However, that's fine if you don't.

**Comment by Horus645** [comment]
Sorry, `ffmpeg` is as much a mystery to me as it's to you :sweat:. Maybe try lowering fps?

**Comment by Froloket64** [comment]
I tried, but it just resulted in dropped frames... Well, I'll keep trying, because I'm _unreasonably committed_ to getting this to work, so I'll post the solution **if/when** I find one.

_Thanks again!_

**Comment by Froloket64** [comment]
Well, turns out using this _simple_ (?) command gets rid of duplicate frames:
``` sh
ffmpeg -i input.gif -vf mpdecimate,setpts=N/FRAME_RATE/TB -an output.gif
```

Combined with other options it looks like this:
``` sh
ffmpeg -i input.gif -filter_complex "mpdecimate,setpts=N/FRAME_RATE/TB,fps=30,scale=1920:1080,split[a][b]; [a]palettegen=stats_mode=full [palette]; [b][palette]paletteuse=dither=sierra2_4a" output.gif
```
