### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by HakierGrzonzo** [Horus645/swww#7]
Hi!

I like your software and I had noticed that it didn't have an AUR package.

So I decided to learn how to package software for AUR, I don't know if it is supposed to be done this way but it installs it with completions. 

Feel free to mention it in `README.md` https://aur.archlinux.org/packages/swww

I had enabled notifications for releases, so I can update the package when you release a new version.

**Comment by Horus645** [comment]
Ooooh. This is pretty neat. I was thinking of doing this but didn't think `swww` was good enough for the AUR yet. I am a bit full today, but I'll look at how to add it to the `README.md` nicely tomorrow.

**Comment by Horus645** [comment]
Done. Thank you once again!
