### ISSUE TITLE
[Feature request] Allow scalling without filtering (for pixel art)

### ISSUE THREAD

**Issue by timeopochin** [Horus645/swww#81]
Hello!

When using animated gif pixel art it would be nice to be able to keep the crispy square pixels even if the original art has a very small resolution compared to the display resolution.

Currently I'm doing the conversion with [gifscicle](https://www.lcdf.org/gifsicle/) but it creates huge gifs which can take up to 10 seconds to be loaded by swww.

When I load the original gif it is loaded almost instantly but clearly has some filtering making the pixels look fuzzy/blurry.

Thanks for such a great application!

**Comment by Horus645** [comment]
Have you tried sending the original image using `--filter=Nearest`?

**Comment by timeopochin** [comment]
Perfect! I knew this would probably already be implemented, I wasn't able to find the option anywhere.

Thank you :)
