### ISSUE TITLE
Smaller sized GIFs don't load on startup, but larger ones do

### ISSUE THREAD

**Issue by WasteOfO2** [Horus645/swww#83]
Hello! I am grateful for this amazing program and love everything about it

I have a small library of GIFs that I use to switch wallpapers from time to time to keep things fresh.

However, I have noticed a peculiar issue where GIFs with smaller sizes (<1MB) sometimes, or don't load at all at startup. However, GIFs with relatively larger sizes (say 2MB and greater) have no issues whatsoever loading in on startup. 

These 2 GIFs are of different resolutions.

Do note, that once I manually execute `swww img /PATH/TO/GIF`, the wallpaper sets itself, regardless of the resolution

I only use a single monitor(1600x900), with my laptop monitor being disabled by the WM itself. 

I am using `hyprland` WM with the following lines in my config file which correspond to my wallpaper set up

```ini
exec-once = swww init
exec-once = swww img /PATH/TO/GIF
```
In both the cases, I have confirmed that `swww init` was running. I am also going to attach the GIFs in question that I have used to test my theory

[This GIF doesn't work](https://files.catbox.moe/ce4fje.gif)
[This GIF works](https://files.catbox.moe/9jgu85.gif)

I am not sure if I can provide any log files, as afaik, `swww` doesn't provide any logging options

**Comment by Horus645** [comment]
I am having trouble reproducing this. You can generate a simple log file by running `swww init --no-daemon`. But that won't be very useful, since we log mostly just errors and warnings at "release". Also note that it will block the current shell.

If you wanted to generate a more useful log you'd have to run the debug version of `swww-daemon`. But I don't think that's all that necessary.

That said I feel like this sentence is incomplete:
> I have noticed a peculiar issue where GIFs with smaller sizes (<1MB) sometimes, or don't load at all at startup.

Sometimes what? I am assuming they aren't animated?

In any case, does this only happen at startup? Have you tried to `swww kill` and `swww init` after startup to see if the issue persists?

Also, just to be clear, are using the latest version, or the current master?

**Comment by Horus645** [comment]
Thinking about it, I don't know if `hyprland` runs those commands in parallel somehow. Does maybe changing your config to 

```
exec-once = swww init && swww img /PATH/TO/GIF
```

improve anything? (the idea is to make sure we only call `swww img` after we are sure the daemon has initialized)

**Comment by WasteOfO2** [comment]
> I am having trouble reproducing this. You can generate a simple log file by running `swww init --no-daemon`. But that won't be very useful, since we log mostly just errors and warnings at "release". Also note that it will block the current shell.
> 
> If you wanted to generate a more useful log you'd have to run the debug version of `swww-daemon`. But I don't think that's all that necessary.
> 
> That said I feel like this sentence is incomplete:
> 
> > I have noticed a peculiar issue where GIFs with smaller sizes (<1MB) sometimes, or don't load at all at startup.
>
> Sometimes what? I am assuming they aren't animated?

I end up with a black screen, I should clarify that it in fact never works for smaller sizes, poor wording on my end
 
> In any case, does this only happen at startup? Have you tried to `swww kill` and `swww init` after startup to see if the issue persists?

Yes this only happens at startup

> Also, just to be clear, are you using the latest version, or the current master?

I am using version 0.7.1, whatever comes packaged with the AUR

>Thinking about it, I don't know if hyprland runs those commands in parallel somehow.

Let's assume that it does, there would be no other way that this issue could possibly be happening otherwise.

`exec-once = swww init && swww img /PATH/TO/GIF`

Let me try this

**Comment by WasteOfO2** [comment]
Can confirm that running both of the commands together actually fixed the issue.

I guess having a bigger file size took _just_ enough time extra for the init command to execute. 

Thanks!
