### ISSUE TITLE
how to compile this app?

### ISSUE THREAD

**Issue by neofeo** [Horus645/swww#95]
Hi, noob question here... never compiled with cargo.
I get this: is listed in workspace’s default-members but is not a member.

**Comment by Horus645** [comment]
have you a set up a proper rust environment?

You need to have `rustc` and `cargo` installed in your system.

Then, you should just run `cargo build --release` and it should build.

How are you trying to compile it right now?

**Comment by neofeo** [comment]
I am on jammy, and yes, installed both and I have that output with cargo.

**Comment by max-ishere** [comment]
They I do it is:
```
git clone 'https://github.com/Horus645/swww/'
cd swww
cargo build --release
```
Not sure why you get this error...

**Comment by neofeo** [comment]
On yeah, I did so. Mmm  maybe its a cargo bug resolved on a newwr release. Closing for now.

**Comment by max-ishere** [comment]
Not sure how this is a cargo bug, but ok...
